### PR TITLE
Added official UIDS buttons

### LINKED ISSUE #27: Integrate proper UIDS 4 buttons
- The "Download All" button should have a gold background
Screen Shot 2022-06-01 at 1 54 41 PM

- The SVG, PNG (1:1), PNG (16:9) buttons are currently in a button group, but I'm not really digging this when the button labels aren't uniform/same length. These could just be buttons and I'd be fine with that
-
Screen Shot 2022-06-01 at 1 54 54 PM

### PR DESCRIPTION
**Pull request by quamsta**
Resolves #27 

I've switched over from a custom component to using the UIDS 4.x button component (tertiary style):

Screen Shot 2022-06-10 at 9 15 30 AM

Screen Shot 2022-06-10 at 9 16 25 AM

### CODE REVIEW

**Comment by bspeare** [comment]
I think this button needs an outline, especially in the modal.    Maybe remove the line above and add the outline?  I think we need to adjust the color of the outline in UIDS.   

Screen Shot 2022-06-15 at 10 48 50 AM

**Comment by quamsta** [comment]
@bspeare I'm also coming around to sharper card-like borders on the icon buttons... Now that we have these sharper borders on the buttons, the softer borders seem a bit out of place

**Comment by bspeare** [comment]
@quamsta I think that looks good.   Is it worth creating a quick pr in UIDS to make these updates for the last two items?  It would be cool to get those in there before we forget.

**Comment by quamsta** [comment]
@bspeare Probably a good call, I don't know how quick I can do it, since I haven't done any PR work in UIDS like, ever and I wanna make sure it's done right. Unless you want to? :P

**Comment by bspeare** [comment]
@quamsta I could start something.  I'll check in with you before I do.

**Comment by quamsta** [comment]
@bspeare Sounds good, I think an overarching button style change/addition may be better in your hands :)

**Comment by bspeare** [comment]
@quamsta I started something https://github.com/uiowa/uids/pull/711 that I will continue to work on.

**Pull request merged**
