### PR TITLE
Search button tweaks

### PR DESCRIPTION
**Pull request by quamsta**
Potentially resolves: https://github.com/uiowa/brand-icon-browser/issues/7

Preview:
Screen Shot 2022-05-25 at 8 37 44 AM

### CODE REVIEW

**Comment by quamsta** [comment]
Ohh got it, I haven't been using Safari lately. Thanks for demoing that. Should be adjusted https://github.com/uiowa/brand-icon-browser/pull/8/commits/560efcd145f2fbad4ece88db483bbae139f1decb

**Comment by GaryRidgway** [comment]
IDK if this is the place to put this,but it feels a little odd to me to have a border on everything but no border on the toggle. have you tried a few designs with that already dustin?

**Comment by quamsta** [comment]
@GaryRidgway Not sure what you mean, can you do some inspector tooling/mocking up and screenshot it? Very visual person over here!

**Comment by GaryRidgway** [comment]
No worries! I am a visual person too, give me just a moment!

**Comment by quamsta** [comment]
@GaryRidgway I'm cool with this-- @bspeare thoughts?

**Comment by quamsta** [comment]
I may prefer no border on the little white circle though
Screen Shot 2022-05-25 at 9 45 20 AM

**Comment by bspeare** [comment]
@GaryRidgway has a good point, the white on gold doesn't pass WCAG AA so we probably should adjust this. If we do have a border, I'd like to see more padding on the toggle.   I think toggle switches are either have enough background contrast so that you don't need a border, or you add a stronger border with more padding. 

Screen Shot 2022-05-25 at 9 50 21 AM

**Comment by GaryRidgway** [comment]
I was just about to say something about the contrast! You beat me to it ben!

**Comment by quamsta** [comment]
Isn't WCAG AA for text over colors, does it also apply to imagery and widgets like the circle and its background?

> Success Criterion [1.4.3 Contrast (Minimum)](https://www.w3.org/TR/WCAG21/#contrast-minimum) (Level AA): The visual presentation of [text](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html#dfn-text) and [images of text](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html#dfn-image-of-text) has a [contrast ratio](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html#dfn-contrast-ratio) of at least 4.5:1, except for the following:

https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

**Comment by quamsta** [comment]
We also have white iconography on [UIDS buttons](https://uids.brand.uiowa.edu/components/detail/button--row.html), see the white arrow on gold:

Screen Shot 2022-05-25 at 10 14 24 AM

**Comment by quamsta** [comment]
I added the border and adjusted the background color of the element (it's a third party component so there's some weird CSS overrides happening), but I'm going to leave the accessibility discussion of icons/graphic elements for another time?

**Comment by bspeare** [comment]
@quamsta sounds good.  We can also reference https://ais-components.its.uiowa.edu/components/AisToggle.html for toggles.  It does seem like the toggle appearance is cleaner without the border.    I don't think every elment needs to have a border.

**Review by bspeare — APPROVED** [review]
Looks good!  Thanks for making this change.

**Pull request merged**
