### PR TITLE
Add brand bar component from UIDS

### LINKED ISSUE #20: Implement brand bar component from UIDS
With https://github.com/uiowa/uids/pull/694 merged, we can now move ahead with implementing the UIDS brand bar in this application.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #20 

# To test
- `npm install`
- `npm serve`

### CODE REVIEW

**Comment by bspeare** [comment]
This looks good, is it ready to review or still in progress?

**Comment by pyrello** [comment]
We should get https://github.com/uiowa/uids/pull/694 merged, then update the commit hash after that. Are we good with keeping the `uids` dependency pinned to a commit hash for now so we don't have to start tagging releases for UIDS 4.x branch yet?

**Comment by quamsta** [comment]
Is using the `4.x` branch in the dependency an option? e.g.

```"uids": "https://github.com/uiowa/uids.git#4.x",```

**Comment by pyrello** [comment]
> Is using the 4.x branch in the dependency an option? e.g.
>
> "uids": "https://github.com/uiowa/uids.git#4.x",

The last two paragraphs in this article sum it up pretty well: https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a

> Installing from a git branch also breaks your ability to run npm update to update the dependency, forcing you to uninstall and reinstall the package in order to pull any new changes pushed to the branch.

> If you are determined to do this, it’s marginally safer to install at a specific commit hash or git tag instead of a branch name. This way your dependency is tied to a specific commit, instead of whatever the latest commit is on a branch. However, the above caveats about disappearing dependencies and broken update paths still apply! You’ve been warned 😉.

We're not as worried about publishing to NPM or broken dependencies (at least for now) since we control the git repos in question.

**Comment by pyrello** [comment]
I'm not sure where, but @bspeare mentioned that maybe we needed to tackle and edge-to-edge brand bar for this. Do we want to do that now? Or is this good enough for the implementation and we can work on that in a future version.

**Comment by quamsta** [comment]
Hypothetically we could add a max-width to the wrapper on `brand-icon-browser` if there's not an edge-to-edge brand bar. The layout gets a little weird after a certain width anyway.

Example of max-width, sort of matching the branding bar:
Screen Shot 2022-05-26 at 8 06 43 AM

**Comment by pyrello** [comment]
Related: https://github.com/uiowa/uids/issues/488

**Comment by quamsta** [comment]
@pyrello I may make a couple of tweaks to some of the icon browser app-specific components (the category sidebar font size and padding, namely and the wrapper max-width) for demoing purpose in this branch. Is that cool?

**Review by quamsta — APPROVED** [review]
I made a couple of tweaks here-and-there to adjust some visual things after the brand bar component was added, and I'm good with taking this to `main`, if you are.

**Pull request merged**
