### PR TITLE
Added feedback links to sidebar and icon modal

### LINKED ISSUE #47: Feedback buttons or links
As a user of the Brand Icon Browser, I'd like to give feedback on any of the following items:

- The Icon Browser app itself
- Individual icons, including how icons are tagged

## Proposed Solution:

Add a link to email [osc-brand@uiowa.edu](mailto:osc-brand@uiowa.edu) in the sidebar and in the icon modal.

### PR DESCRIPTION
**Pull request by quamsta**
Resolves #47 
Screen Shot 2022-06-14 at 4 34 19 PM
Screen Shot 2022-06-14 at 4 34 29 PM

### CODE REVIEW

**Comment by bspeare** [comment]
It looks good in the sidebar.  Any chance to we can avoid placing it in the modal?  There's already a lot going on in there.

**Comment by quamsta** [comment]
@bspeare Yeah, that's fine, a more general feedback link can work for both purposes (general feedback + icon feedback) anyway

**Comment by quamsta** [comment]
@bspeare removed from modal

**Review by bspeare — APPROVED** [review]
Looks good!

**Pull request merged**
