### PR TITLE
Show checkerboard pattern on icon preview

### LINKED ISSUE #30: Checkerboard pattern to indicate PNG alpha channel transparency in variation preview
From @GaryRidgway:

> Is it possible to change the BG on white lined icons to a checkered Background? The first time I saw them, considering they were PNG only, I thought that it was a black square with a white lined icon over top.

### PR DESCRIPTION
**Pull request by quamsta**
Resolves #30

Screen Shot 2022-06-08 at 11 19 51 AM
Screen Shot 2022-06-08 at 11 21 31 AM

### CODE REVIEW

**Comment by bspeare** [comment]
Do you think people will still be confused by the transparent black background?  I could see this use the same background for all options.

**Comment by quamsta** [comment]
@bspeare can you clarify a bit? I use a darker checkerboard pattern on the white lined-items only just because the alternative is too hard to see:

Screen Shot 2022-06-08 at 2 47 12 PM

Are you asking if we can just not use a darker checkerboard pattern?

**Comment by bspeare** [comment]
Yes, I think showing it as you have in your screenshot is the way to go.  Here's what the noun project does:

Screen Shot 2022-06-08 at 2 52 44 PM

**Comment by quamsta** [comment]
@bspeare 

Yeah it might make it more clear that you're getting the "full transparency experience" with the consistent bg. I'm fine with that. If we hear a lot of feedback about that one being hard to see, maybe we can revisit?

**Comment by quamsta** [comment]
@bspeare Removed that darker checkerboard pattern, this should always default to the normal pattern now

**Review by bspeare — APPROVED** [review]
I think this helps a lot, thanks!

**Pull request merged**
